## This file is a general .xdc for the Eclypse Z7 Rev. B.0
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

## 125MHz Clock from Ethernet PHY
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports clk125mhz]
create_clock -period 8.000 -name sys_clk_pin -waveform {0.000 4.000} -add [get_ports clk125mhz]

## RGB LEDs
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS33} [get_ports {or3_led0[0]}]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS33} [get_ports {or3_led0[1]}]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports {or3_led0[2]}]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS33} [get_ports {or3_led1[0]}]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33} [get_ports {or3_led1[1]}]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVCMOS33} [get_ports {or3_led1[2]}]

## Syzygy Port A
set_property -dict {PACKAGE_PIN N19 IOSTANDARD LVCMOS18} [get_ports o_dac_clkout]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS18} [get_ports o_dac_fsadjq]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS18} [get_ports o_dac_fsadji]
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS18} [get_ports {o14_dac_data[12]}]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS18} [get_ports {o14_dac_data[13]}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS18} [get_ports o_dac_sck]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS18} [get_ports o_dac_rst]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS18} [get_ports {o14_dac_data[10]}]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS18} [get_ports {o14_dac_data[11]}]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS18} [get_ports o_dac_cs]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS18} [get_ports o_dac_sdio]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS18} [get_ports {o14_dac_data[8]}]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS18} [get_ports {o14_dac_data[9]}]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS18} [get_ports {o14_dac_data[2]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS18} [get_ports or_zmod_dac_relay]
set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS18} [get_ports {o14_dac_data[6]}]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS18} [get_ports {o14_dac_data[7]}]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS18} [get_ports o_dac_dclkio]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS18} [get_ports {o14_dac_data[4]}]
set_property -dict {PACKAGE_PIN K20 IOSTANDARD LVCMOS18} [get_ports {o14_dac_data[5]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS18} [get_ports {o14_dac_data[1]}]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVCMOS18} [get_ports {o14_dac_data[0]}]
set_property -dict {PACKAGE_PIN L22 IOSTANDARD LVCMOS18} [get_ports {o14_dac_data[3]}]

## Syzygy Port B
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD DIFF_HSTL_I_18} [get_ports o_adc_clkout_n]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD DIFF_HSTL_I_18} [get_ports o_adc_clkout_p]
set_property -dict {PACKAGE_PIN Y15 IOSTANDARD LVCMOS18} [get_ports o_zmod_adc_coupling_l_a]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVCMOS18} [get_ports o_zmod_adc_coupling_h_a]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS18} [get_ports o_zmod_adc_coupling_l_b]
set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVCMOS18} [get_ports o_zmod_adc_coupling_h_b]
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVCMOS18} [get_ports o_adc_sck]
set_property -dict {PACKAGE_PIN Y13 IOSTANDARD LVCMOS18} [get_ports o_adc_sdio]
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD LVCMOS18} [get_ports o_zmod_adc_gain_l_b]
set_property -dict {PACKAGE_PIN AB14 IOSTANDARD LVCMOS18} [get_ports o_zmod_adc_gain_h_b]
set_property -dict {PACKAGE_PIN AA14 IOSTANDARD LVCMOS18} [get_ports {i14_adc_data[2]}]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS18} [get_ports {i14_adc_data[9]}]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS18} [get_ports o_zmod_adc_gain_l_a]
set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS18} [get_ports o_zmod_adc_gain_h_a]
set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVCMOS18} [get_ports {i14_adc_data[4]}]
set_property -dict {PACKAGE_PIN AA22 IOSTANDARD LVCMOS18} [get_ports {i14_adc_data[3]}]
set_property -dict {PACKAGE_PIN Y21 IOSTANDARD LVCMOS18} [get_ports o_zmod_adc_com_l]
set_property -dict {PACKAGE_PIN Y20 IOSTANDARD LVCMOS18} [get_ports o_zmod_adc_com_h]
#set_property -dict { PACKAGE_PIN W18 IOSTANDARD LVCMOS18} [get_ports { }]; #IO_L13N_T2_MRCC Sch=syzygy_b_p2c_clk_n
set_property -dict {PACKAGE_PIN W17 IOSTANDARD LVCMOS18} [get_ports i_adc_dco]
set_property -dict {PACKAGE_PIN AA18 IOSTANDARD LVCMOS18} [get_ports {i14_adc_data[5]}]
set_property -dict {PACKAGE_PIN AA19 IOSTANDARD LVCMOS18} [get_ports {i14_adc_data[8]}]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS18} [get_ports {i14_adc_data[6]}]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS18} [get_ports {i14_adc_data[10]}]
set_property -dict {PACKAGE_PIN AB20 IOSTANDARD LVCMOS18} [get_ports {i14_adc_data[7]}]
set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVCMOS18} [get_ports {i14_adc_data[11]}]
set_property -dict {PACKAGE_PIN AB19 IOSTANDARD LVCMOS18} [get_ports {i14_adc_data[1]}]
set_property -dict {PACKAGE_PIN AA21 IOSTANDARD LVCMOS18} [get_ports {i14_adc_data[12]}]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS18} [get_ports {i14_adc_data[0]}]
set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVCMOS18} [get_ports {i14_adc_data[13]}]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS18} [get_ports o_adc_cs]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS18} [get_ports o_adc_sync]

### Pmod Header JA
#set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports { o_ja[0] }]; #IO_0 Sch=ja1_fpga
#set_property -dict { PACKAGE_PIN H18   IOSTANDARD LVCMOS33 } [get_ports { o_ja[1] }]; #IO_25 Sch=ja2_fpga
#set_property -dict { PACKAGE_PIN E16   IOSTANDARD LVCMOS33 } [get_ports { o_ja[2] }]; #IO_L1N_T0_AD0N Sch=ja3_fpga
#set_property -dict { PACKAGE_PIN F16   IOSTANDARD LVCMOS33 } [get_ports { o_ja[3] }]; #IO_L1P_T0_AD0P Sch=ja4_fpga
#set_property -dict { PACKAGE_PIN D17   IOSTANDARD LVCMOS33 } [get_ports { o_ja[4] }]; #IO_L2N_T0_AD8N Sch=ja7_fpga
#set_property -dict { PACKAGE_PIN D16   IOSTANDARD LVCMOS33 } [get_ports { o_ja[5] }]; #IO_L2P_T0_AD8P Sch=ja8_fpga
#set_property -dict { PACKAGE_PIN D15   IOSTANDARD LVCMOS33 } [get_ports { o_ja[6] }]; #IO_L3N_T0_DQS_AD1N Sch=ja9_fpga
#set_property -dict { PACKAGE_PIN E15   IOSTANDARD LVCMOS33 } [get_ports { o_ja[7] }]; #IO_L3P_T0_DQS_AD1P Sch=ja10_fpga

set_property MARK_DEBUG true [get_nets i_adc_dco_IBUF]

set_property MARK_DEBUG true [get_nets {or14_data_a[4]}]
set_property MARK_DEBUG true [get_nets {or14_data_a[3]}]
set_property MARK_DEBUG true [get_nets {or14_data_a[9]}]
set_property MARK_DEBUG true [get_nets {or14_data_a[8]}]
set_property MARK_DEBUG true [get_nets {or14_data_a[11]}]
set_property MARK_DEBUG true [get_nets {or14_data_a[12]}]
set_property MARK_DEBUG true [get_nets {or14_data_a[13]}]
set_property MARK_DEBUG true [get_nets {or14_data_a[6]}]
set_property MARK_DEBUG true [get_nets {or14_data_a[10]}]
set_property MARK_DEBUG true [get_nets {or14_data_a[7]}]
set_property MARK_DEBUG true [get_nets {or14_data_a[2]}]
set_property MARK_DEBUG true [get_nets {or14_data_a[5]}]
set_property MARK_DEBUG true [get_nets {or14_data_a[0]}]
set_property MARK_DEBUG true [get_nets {or14_data_a[1]}]

connect_debug_port u_ila_0/probe0 [get_nets [list {or14_data_a[0]} {or14_data_a[1]} {or14_data_a[2]} {or14_data_a[3]} {or14_data_a[4]} {or14_data_a[5]} {or14_data_a[6]} {or14_data_a[7]} {or14_data_a[8]} {or14_data_a[9]} {or14_data_a[10]} {or14_data_a[11]} {or14_data_a[12]} {or14_data_a[13]}]]


set_property MARK_DEBUG true [get_nets {i14_adc_data_IBUF[3]}]
set_property MARK_DEBUG true [get_nets {i14_adc_data_IBUF[0]}]
set_property MARK_DEBUG true [get_nets {i14_adc_data_IBUF[12]}]
set_property MARK_DEBUG true [get_nets {i14_adc_data_IBUF[13]}]
set_property MARK_DEBUG true [get_nets {i14_adc_data_IBUF[1]}]
set_property MARK_DEBUG true [get_nets {i14_adc_data_IBUF[2]}]
set_property MARK_DEBUG true [get_nets {i14_adc_data_IBUF[4]}]
set_property MARK_DEBUG true [get_nets {i14_adc_data_IBUF[5]}]
set_property MARK_DEBUG true [get_nets {i14_adc_data_IBUF[6]}]
set_property MARK_DEBUG true [get_nets {i14_adc_data_IBUF[7]}]
set_property MARK_DEBUG true [get_nets {i14_adc_data_IBUF[8]}]
set_property MARK_DEBUG true [get_nets {i14_adc_data_IBUF[9]}]
set_property MARK_DEBUG true [get_nets {i14_adc_data_IBUF[10]}]
set_property MARK_DEBUG true [get_nets {i14_adc_data_IBUF[11]}]
set_property MARK_DEBUG true [get_nets {w14_data_a_adc[3]}]
set_property MARK_DEBUG true [get_nets {w14_data_a_adc[0]}]
set_property MARK_DEBUG true [get_nets {w14_data_a_adc[1]}]
set_property MARK_DEBUG true [get_nets {w14_data_a_adc[2]}]
set_property MARK_DEBUG true [get_nets {w14_data_a_adc[4]}]
set_property MARK_DEBUG true [get_nets {w14_data_a_adc[5]}]
set_property MARK_DEBUG true [get_nets {w14_data_a_adc[6]}]
set_property MARK_DEBUG true [get_nets {w14_data_a_adc[7]}]
set_property MARK_DEBUG true [get_nets {w14_data_a_adc[8]}]
set_property MARK_DEBUG true [get_nets {w14_data_a_adc[9]}]
set_property MARK_DEBUG true [get_nets {w14_data_a_adc[10]}]
set_property MARK_DEBUG true [get_nets {w14_data_a_adc[11]}]
set_property MARK_DEBUG true [get_nets {w14_data_a_adc[12]}]
set_property MARK_DEBUG true [get_nets {w14_data_a_adc[13]}]
set_property MARK_DEBUG false [get_nets {o14_dac_data_OBUF[3]}]
set_property MARK_DEBUG false [get_nets {o14_dac_data_OBUF[0]}]
set_property MARK_DEBUG false [get_nets {o14_dac_data_OBUF[12]}]
set_property MARK_DEBUG false [get_nets {o14_dac_data_OBUF[13]}]
set_property MARK_DEBUG false [get_nets {o14_dac_data_OBUF[1]}]
set_property MARK_DEBUG false [get_nets {o14_dac_data_OBUF[2]}]
set_property MARK_DEBUG false [get_nets {o14_dac_data_OBUF[4]}]
set_property MARK_DEBUG false [get_nets {o14_dac_data_OBUF[5]}]
set_property MARK_DEBUG false [get_nets {o14_dac_data_OBUF[6]}]
set_property MARK_DEBUG false [get_nets {o14_dac_data_OBUF[7]}]
set_property MARK_DEBUG false [get_nets {o14_dac_data_OBUF[8]}]
set_property MARK_DEBUG false [get_nets {o14_dac_data_OBUF[9]}]
set_property MARK_DEBUG false [get_nets {o14_dac_data_OBUF[10]}]
set_property MARK_DEBUG false [get_nets {o14_dac_data_OBUF[11]}]

set_property MARK_DEBUG true [get_nets {adc_zmod/i14_data[0]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/i14_data[1]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/i14_data[2]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/i14_data[3]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/i14_data[4]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/i14_data[5]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/i14_data[6]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/i14_data[7]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/i14_data[8]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/i14_data[9]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/i14_data[10]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/i14_data[11]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/i14_data[12]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/i14_data[13]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_a[5]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_a[6]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_a[1]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_a[2]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_a[3]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_a[4]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_a[7]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_a[8]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_a[13]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_a[9]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_a[10]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_a[11]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_a[12]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_a[0]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_b[4]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_b[0]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_b[12]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_b[11]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_b[1]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_b[2]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_b[3]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_b[5]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_b[6]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_b[7]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_b[8]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_b[9]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_b[10]}]
set_property MARK_DEBUG true [get_nets {adc_zmod/o14_data_b[13]}]
set_property MARK_DEBUG true [get_nets adc_zmod/i_dco]
connect_debug_port u_ila_0/probe3 [get_nets [list i_adc_dco_IBUF]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 14 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {i14_adc_data_IBUF[0]} {i14_adc_data_IBUF[1]} {i14_adc_data_IBUF[2]} {i14_adc_data_IBUF[3]} {i14_adc_data_IBUF[4]} {i14_adc_data_IBUF[5]} {i14_adc_data_IBUF[6]} {i14_adc_data_IBUF[7]} {i14_adc_data_IBUF[8]} {i14_adc_data_IBUF[9]} {i14_adc_data_IBUF[10]} {i14_adc_data_IBUF[11]} {i14_adc_data_IBUF[12]} {i14_adc_data_IBUF[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 14 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {adc_zmod/o14_data_b[0]} {adc_zmod/o14_data_b[1]} {adc_zmod/o14_data_b[2]} {adc_zmod/o14_data_b[3]} {adc_zmod/o14_data_b[4]} {adc_zmod/o14_data_b[5]} {adc_zmod/o14_data_b[6]} {adc_zmod/o14_data_b[7]} {adc_zmod/o14_data_b[8]} {adc_zmod/o14_data_b[9]} {adc_zmod/o14_data_b[10]} {adc_zmod/o14_data_b[11]} {adc_zmod/o14_data_b[12]} {adc_zmod/o14_data_b[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 14 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {adc_zmod/o14_data_a[0]} {adc_zmod/o14_data_a[1]} {adc_zmod/o14_data_a[2]} {adc_zmod/o14_data_a[3]} {adc_zmod/o14_data_a[4]} {adc_zmod/o14_data_a[5]} {adc_zmod/o14_data_a[6]} {adc_zmod/o14_data_a[7]} {adc_zmod/o14_data_a[8]} {adc_zmod/o14_data_a[9]} {adc_zmod/o14_data_a[10]} {adc_zmod/o14_data_a[11]} {adc_zmod/o14_data_a[12]} {adc_zmod/o14_data_a[13]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk100mhz]
